# Generated by Django 5.2.1 on 2025-05-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('autor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True, null=True)),
                ('fecha_Salida', models.DateField(auto_now_add=True, null=True)),
                ('pagina', models.IntegerField(blank=True, default=None, null=True)),
                ('secuencia', models.IntegerField(blank=True, default=None, null=True)),
                ('estado', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('estado_anterior', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
