# Generated by Django 5.2.1 on 2025-05-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='oferta',
            constraint=models.UniqueConstraint(fields=('nombre', 'autor'), name='unique_libro'),
        ),
    ]
