# Generated by Django 5.2.1 on 2025-05-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0002_oferta_unique_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='fecha_Salida',
            new_name='fecha_salida',
        ),
    ]
