# Generated by Django 5.2.1 on 2025-05-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0004_rename_precio_oferta_precio_en_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='precio_en_texto',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
