# Generated by Django 5.2.1 on 2025-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0005_alter_oferta_precio_en_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
