# Generated by Django 5.2.1 on 2025-05-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0006_alter_oferta_fecha_ingreso_alter_oferta_fecha_salida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
