# Generated by Django 5.2.1 on 2025-05-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0008_remove_oferta_unique_libro'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='oferta',
            constraint=models.UniqueConstraint(fields=('titulo', 'autor'), name='unique_libro'),
        ),
    ]
