# Generated by Django 5.2.1 on 2025-05-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0009_oferta_unique_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='enlace',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
