# Generated by Django 5.2.1 on 2025-05-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0010_oferta_enlace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='estado',
            new_name='disponibilidad',
        ),
    ]
