# Generated by Django 5.2.1 on 2025-05-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ofertas', '0012_oferta_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='estado_anterior',
            new_name='disponibilidad_anterior',
        ),
    ]
